#!/usr/bin/env bash
#
# Used to search git aliases.
# If no parameter is used, show all aliases.
#
# $1 - Alias to search for.
#
#
# Examples
#
#   git alias
#   git alias secret-alias
#

if [ "$1" == "" ]; then
    git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
else
    git alias | grep -e "$1"
fi
