#!/bin/bash

PULL_REQUEST_ID="$1"
BRANCH_NAME="$2"
upstream=0
git_remotes=($(git remote))

for git_remote in "${git_remotes[@]}"; do
    if [ "$git_remote" == "upstream" ]; then
        upstream=1
    fi
done

function usage() {
    cat <<EOF
Usage:
  git fetch-pull-request [pull request id] [destination branch]

ex:
  git fetch-pull-request 1024 pull-request-branch
EOF
}

if [ "$PULL_REQUEST_ID" == "" -o "$BRANCH_NAME" == "" ]; then
    usage
    exit 1
elif [ "$PULL_REQUEST_ID" == "-h" -o "$PULL_REQUEST_ID" == "--help" ]; then
    usage
    exit 0
fi

if [ $upstream -eq 1 ]; then
    git fetch upstream "pull/${PULL_REQUEST_ID}/head:${BRANCH_NAME}"
else
    git fetch origin "pull/${PULL_REQUEST_ID}/head:${BRANCH_NAME}"
fi
