#!/usr/bin/env bash
#
# Updates the local master.
# If the upstream remote is present, updates the local master with the
# upstream master.
#
#
# Examples
#
#   git up
#

set -e

git_remotes=($(git remote))

upstream=0
for git_remote in "${git_remotes[@]}"; do
    if [ "$git_remote" == "upstream" ]; then
        upstream=1
    fi
done

if [ $upstream -eq 1 ]; then
    git fetch --all --prune
    git pull --prune --rebase
    git fetch upstream
    if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
        git merge --ff-only upstream/master
    fi
else
    git fetch --all --prune
    git pull --prune --rebase
fi

git submodule update --init --recursive
