#!/bin/bash

BRANCH_NAME="$1"

set -e

function usage() {
    cat <<EOF
Usage:
  git branch-squash [branch name]

ex:
  git branch-squash shiny-feature
EOF
}

if [ "$BRANCH_NAME" == "" ]; then
    usage
    exit 1
elif [ "$BRANCH_NAME" == "-h" -o "$BRANCH_NAME" == "--help" ]; then
    usage
    exit 0
fi

author=$(git --no-pager show -s --format='%an <%ae>' "${BRANCH_NAME}")
git merge --squash "${BRANCH_NAME}"
git commit
git commit -C HEAD --amend --author "$author"
git branch -D "${BRANCH_NAME}"
