#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
gitconfig_lib_path=~/.gitconfig.lib

[ -e "$gitconfig_lib_path" ] && unlink "$gitconfig_lib_path"
ln -s "$dir/gitconfig.lib" "$gitconfig_lib_path"

if [ -e ~/.gitconfig ]; then
    grep -q "$gitconfig_lib_path" ~/.gitconfig ||
        echo -e "\n[include]\n  path = $gitconfig_lib_path" \
        > ~/.gitconfig
else
    echo -e "\n[include]\n  path = $gitconfig_lib_path" > ~/.gitconfig
fi
