#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
vimrc=~/.vimrc
nvim_init=~/.config/nvim/init.vim

[[ -e "$vimrc" ]] && unlink "$vimrc"
ln -s "$dir/vimrc" "$vimrc"

mkdir -p ~/.config/nvim
[[ -e "$nvim_init" ]] && unlink "$nvim_init"
ln -s "$dir/vimrc" "$nvim_init"

if [ ! -e ~/.vim-plug ]; then
    git clone https://github.com/junegunn/vim-plug.git ~/.vim-plug
else
    pushd ~/.vim-plug > /dev/null
    git pull > /dev/null
    popd > /dev/null
fi

if [ ! -e ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    ln -s ~/.vim-plug/plug.vim ~/.vim/autoload/plug.vim
fi

if [ ! -e ~/.config/nvim/autoload/plug.vim ]; then
    mkdir -p ~/.config/nvim/autoload
    ln -s ~/.vim-plug/plug.vim ~/.config/nvim/autoload/plug.vim
fi
