set rtp+=~/.local/lib/python3.5/site-packages/powerline/bindings/vim

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'Shougo/vimproc.vim'

Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'vim-scripts/gitignore'

Plug 'ctrlpvim/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'Raimondi/delimitMate'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'ervandew/supertab'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/incsearch.vim'

Plug 'Valloric/YouCompleteMe', { 'do': './install.py --gocode-completer --tern-completer' }
Plug 'scrooloose/syntastic'
Plug 'Chiel92/vim-autoformat'
Plug 'tpope/vim-dispatch'
Plug 'tmhedberg/SimpylFold'

Plug 'mattn/emmet-vim'
Plug 'helino/vim-json'
Plug 'jelera/vim-javascript-syntax'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'ternjs/tern_for_vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'skammer/vim-css-color'
Plug 'alvan/vim-closetag'

Plug 'fisadev/vim-isort'
Plug 'davidhalter/jedi-vim'

Plug 'fatih/vim-go'

Plug 'w0ng/vim-hybrid'

call plug#end()

syntax on
filetype on
filetype plugin indent on
set clipboard=unnamedplus

if has('nvim')
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
else
  let g:rehash256 = 1
  set t_Co=256
endif

if has('gui_running')
  set guifont=Source\ Code\ Pro\ for\ Powerline\ Medium\ 11
endif

set background=dark
colorscheme hybrid

map <C-w>e :split<CR>
map <C-w>q :vsplit<CR>
map <C-d><Left> :tabprevious<CR>
map <C-d><Right> :tabnext<CR>
map <C-d>c :tabnew<CR>

map <F3> :NERDTreeToggle<CR>
map <F8> :TagbarToggle<CR>
map <F9> :Dispatch<CR>
map <C-_> :Commentary<CR>
map <C-b> :CtrlPBuffer<CR>

map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" <Leader>f{char} to move to {char}
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)

" s{char}{char} to move to {char}{char}
nmap s <Plug>(easymotion-overwin-f2)

" Move to line
map <Leader>L <Plug>(easymotion-bd-jk)
nmap <Leader>L <Plug>(easymotion-overwin-line)

" Move to word
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)

set wildignore+=*/tmp/*,*/node_modules/*,*.so,*.swp,*.zip,*.gz,*.xz,*.tar

let loaded_netrwPlugin=1
let NERDTreeRespectWildIgnore=1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree())

let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3

set foldlevelstart=99

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set laststatus=2
set showtabline=2

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

let g:closetag_filenames = "*.html,*.template,*.jinja2"
let g:javascript_plugin_jsdoc = 1

let g:syntastic_json_checkers = ['jsonlint']
let g:syntastic_yaml_checkers = ['jsyaml']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_python_checkers = ['python', 'pylint']
let g:syntastic_go_checkers = ['go', 'gofmt', 'golint']
let g:syntastic_sh_checkers = ['shellcheck']
let g:syntastic_rst_checkers = ['sphinx', 'rstcheck']
let g:syntastic_tex_checkers = []

let g:syntastic_python_pylint_args = '--rcfile=.pylintrc'

let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall

autocmd bufwritepost *.py silent !isort %
set autoread

au BufWrite * :Autoformat
let g:formatdef_yapf = "'yapf'"
let g:formatters_python = ['yapf']
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
