#!/bin/bash

set -e

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

PKGS=(
  "flathub org.freedesktop.Platform.Icontheme.Adwaita"
  "flathub org.kde.KStyle.Adwaita//5.10"
  "flathub org.kde.PlatformTheme.QGnomePlatform//5.10"
  "flathub org.keepassxc.KeePassXC"
  "flathub com.spotify.Client"
  "flathub com.valvesoftware.Steam"
  "flathub org.gnome.Games"
)

for pkg in "${PKGS[@]}"; do
  pkg=($pkg)
  repo="${pkg[0]}"
  pkg="${pkg[1]}"
  flatpak install -y "$repo" "$pkg"
done
