#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
editorconfig_path=~/.editorconfig

[ -L "$editorconfig_path" -o -e "$editorconfig_path" ] && unlink "$editorconfig_path"
ln -s "$dir/config" "$editorconfig_path"
