#!/bin/bash

FONT_URL='https://github.com/source-foundry/Hack/releases/download/v3.000/Hack-v3.000-ttf.zip'

mkdir -p ~/.fonts
cd ~/.fonts
wget -O Hack.zip "${FONT_URL}"
unzip Hack.zip
mv ttf/*.ttf .
rm -rf ttf/
rm Hack.zip

dconf write /org/gnome/desktop/interface/monospace-font-name "'Hack Regular 10'"
