#!/bin/bash

builtin cd "$(dirname "${BASH_SOURCE[0]}")/.."

brew update && brew bundle
outdated_pkgs=($(brew outdated))
if [[ "${outdated_pkgs[@]}" -ne "" ]]; then
    brew upgrade "${outdated_pkgs[@]}"
fi

CATEGORIES=(
    bin
    editorconfig
    elementaryos
    fonts
    git
    python
    powerline
    tmux
    zsh
    vim
    atom
)

for category_dir in "${CATEGORIES[@]}"; do
    category_dir="${category_dir##*/}"
    if [ -e "$category_dir/install" ] & [ "$category_dir" != "script" ]; then
        "./$category_dir/install"
    fi
done
