#!/bin/bash

builtin cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ ! -f "$HOME/.linuxbrew/bin/brew" ]; then
    git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
fi
export PATH="$HOME/.linuxbrew/bin:$PATH"

brew update && brew bundle
outdated_pkgs=($(brew outdated))
if [[ "${outdated_pkgs[@]}" -ne "" ]]; then
    brew upgrade "${outdated_pkgs[@]}"
fi

CATEGORIES=(
    bin
    editorconfig
    fonts
    git
    python
    powerline
    tmux
    zsh
    nvim
    atom
)

for category_dir in "${CATEGORIES[@]}"; do
    category_dir="${category_dir##*/}"
    if [ -e "$category_dir/install" ] & [ "$category_dir" != "script" ]; then
        "./$category_dir/install"
    fi
done
