#!/bin/bash

ASDF_DIR="$HOME/.asdf"
ASDF_VERSION="v0.13.1"

if [ ! -d "$ASDF_DIR" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch "$ASDF_VERSION"
fi

source "$ASDF_DIR/asdf.sh"
asdf plugin add nodejs
asdf plugin add golang
asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf plugin add terragrunt https://github.com/ohmer/asdf-terragrunt

asdf install nodejs 20.9.0
asdf install golang 1.21.4
asdf install terraform 1.6.3
asdf install terragrunt 0.53.2

asdf global nodejs 20.9.0
asdf global golang 1.21.4
asdf global terraform 1.6.3
asdf global terragrunt 0.53.2
