#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
tmux_conf=~/.tmux.conf

[[ -e "$tmux_conf" || -L "$tmux_conf" ]] && unlink "$tmux_conf"
ln -s "$dir/tmux.conf" "$tmux_conf"
