#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
tmux_conf=~/.tmux.conf

[[ -e "$tmux_conf" || -L "$tmux_conf" ]] && unlink "$tmux_conf"
ln -s "$dir/tmux.conf" "$tmux_conf"

mkdir -p $HOME/.tmux/plugins
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
