#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ ! -e ~/.zprezto ]]; then
    git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

for zsh_config in "$dir"/*; do
    [[ "${zsh_config##*/}" == "install" ]] && continue
    [[ -e ~/."${zsh_config##*/}" || -L ~/."${zsh_config##*/}" ]] && unlink ~/."${zsh_config##*/}"
    ln -s "$zsh_config" ~/."${zsh_config##*/}"
done
