#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for zsh_config in "$dir"/*; do
    [[ "${zsh_config##*/}" == "install" ]] && continue
    [[ -e ~/."${zsh_config##*/}" ]] && unlink ~/."${zsh_config##*/}"
    ln -s "$zsh_config" ~/."${zsh_config##*/}"
done
