#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[[ ! -d ~/.zsh ]] && mkdir ~/.zsh
[[ ! -d ~/.zsh/lib ]] && mkdir ~/.zsh/lib
[[ ! -d ~/.zkbd ]] && mkdir ~/.zkbd

for zsh_config in "$dir"/*.zsh; do
    [[ -e ~/.zsh/"${zsh_config##*/}" || -L ~/.zsh/"${zsh_config##*/}" ]] && unlink ~/.zsh/"${zsh_config##*/}"
    ln -s "$zsh_config" ~/.zsh/"${zsh_config##*/}"
done

for zsh_lib in "$dir"/lib/*.zsh; do
    [[ -e ~/.zsh/lib/"${zsh_lib##*/}" || -L ~/.zsh/lib/"${zsh_lib##*/}" ]] && unlink ~/.zsh/lib/"${zsh_lib##*/}"
    ln -s "$zsh_lib" ~/.zsh/"${zsh_lib##*/}"
done

[[ -e ~/.zsh/plugins || -L ~/.zsh/plugins ]] && unlink ~/.zsh/plugins
ln -s "$dir/plugins" ~/.zsh/plugins

[[ -e "$HOME/.zkbd/screen-256color-:0" || -L "$HOME/.zkbd/screen-256color-:0" ]] && unlink "$HOME/.zkbd/screen-256color-:0"
ln -s "$dir/zkbd.screen-256color" "$HOME/.zkbd/screen-256color-:0"

[[ -e "$HOME/.zkbd/xterm-256color-:0" || -L "$HOME/.zkbd/xterm-256color-:0" ]] && unlink "$HOME/.zkbd/xterm-256color-:0"
ln -s "$dir/zkbd.xterm-256color" "$HOME/.zkbd/xterm-256color-:0"

[[ -e ~/.zshrc || -L ~/.zshrc ]] && unlink ~/.zshrc
ln -s "$dir/zshrc" ~/.zshrc

mkdir -p ~/bin
curl -L https://github.com/getantibody/antibody/releases/download/v3.1.3/antibody_Linux_x86_64.tar.gz | tar -C ~/bin -xzf - antibody
