#!/bin/zsh
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# load antibody plugins
source <(antibody init)
source ~/.zsh/plugins

typeset -U config_files
config_files=($HOME/.zsh/*.zsh)

# load the path files
for file in ${config_files[@]}; do
  source "$file"
done

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

if [ -e ~/.customrc.sh ]; then
  source ~/.customrc.sh
else
  touch ~/.customrc.sh
fi
