#!/bin/zsh
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

if [ ! -e ~/.customrc.sh ] || [ ! -s ~/.customrc.sh ]; then
  cat <<EOF > ~/.customrc.sh
#!/bin/bash

#ZSH_THEME_PLUGIN=tcnksm/oh-my-zsh-beer-theme
#ZSH_PLUGINS=(
#  gko/ssh-connect
#)

custom_init() {
  #do something
}
EOF
fi

source ~/.customrc.sh

# load antibody plugins
source <(antibody init)
source ~/.zsh/plugins

# load the lang config files
typeset -U config_files
config_files=($HOME/.zsh/*.zsh)
for file in ${config_files[@]}; do
  source "$file"
done

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

declare -f -F custom_init > /dev/null && custom_init
