#!/bin/bash

dir="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for script in "$dir"/wine-*; do
    mkdir -p ~/bin
    [[ -e ~/bin/"${script##*/}" ]] && unlink ~/bin/"${script##*/}"
    ln -s "$script" ~/bin/
done
