#!/bin/bash

WINEPREFIX="$1"
shift
WINEARCH="$1"
shift
EXECUTABLE="$1"
shift

WINEDEBUG=-all
NVIDIA=1

while [ "$1" != "" ]; do
    OPT=$1
    case "$1" in
    cfg)
        WINEPREFIX="$WINEPREFIX" WINEARCH="$WINEARCH" winecfg
        exit $?
        ;;
    tricks)
        WINEPREFIX="$WINEPREFIX" WINEARCH="$WINEARCH" winetricks
        exit $?
        ;;
    debug)
        WINEDEBUG=""
        ;;
    debug-all)
        WINEDEBUG=+all
        ;;
    nonvidia)
        NVIDIA=0
        ;;
    esac
    shift
done

if [ $NVIDIA -eq 1 ]; then
    WINEDEBUG="$WINEDEBUG" WINEPREFIX="$WINEPREFIX" WINEARCH="$WINEARCH" primusrun wine "$EXECUTABLE"
else
    WINEDEBUG="$WINEDEBUG" WINEPREFIX="$WINEPREFIX" WINEARCH="$WINEARCH" wine "$EXECUTABLE"
fi
