#!/bin/bash

WINEPREFIX="$HOME/.wine_prefix/steam"
WINEARCH=win32
EXECUTABLE="$HOME/.wine_prefix/steam/drive_c/Program Files/Steam/Steam.exe"
OPT="$1"

wine-prefix-exec "$WINEPREFIX" "$WINEARCH" "$EXECUTABLE" "$OPT"
