#!/bin/bash

WINEPREFIX="$HOME/.wine_prefix/battle.net"
WINEARCH=win32
EXECUTABLE="$HOME/.wine_prefix/battle.net/drive_c/Program Files/Battle.net/Battle.net Launcher.exe"
OPT="$1"

wine-prefix-exec "$WINEPREFIX" "$WINEARCH" "$EXECUTABLE" "$OPT"
