#!/bin/bash

WINEPREFIX="$HOME/.wine_prefix/path_of_exile"
WINEARCH=win32
EXECUTABLE="$HOME/.wine_prefix/path_of_exile/drive_c/Program Files/Grinding Gear Games/Path of Exile/PathOfExile.exe"

wine-prefix-exec "$WINEPREFIX" "$WINEARCH" "$EXECUTABLE" "$@"
