#!/bin/bash

export WINEDEBUG=-all
export WINEPREFIX=$HOME/.wine_prefix/steam
export WINEARCH=win32
CMD="$WINEPREFIX/drive_c/Program Files/Steam/Steam.exe"


case "$1" in
    no-nvidia)
        wine $CMD
        ;;
    winecfg)
        winecfg
        ;;
    debug)
        WINEDEBUG='' wine "$CMD"
        ;;
    *)
        primusrun wine "$CMD"
        ;;
esac
