#!/bin/bash

WINEPREFIX="$HOME/.wine_prefix/final_fantasy_xiv"
WINEARCH=win32
EXECUTABLE="$HOME/.wine_prefix/final_fantasy_xiv/drive_c/Program Files/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/boot/ffxivboot.exe"

wine-prefix-exec "$WINEPREFIX" "$WINEARCH" "$EXECUTABLE" "$@"
